/*
 * |--------------------------------------------------------------|
 * |                                                              |
 * |                   DO NOT DELETE THIS FILE!                   |
 * |                                                              |
 * |  THIS IS THE CORE APPLICATION FILE FOR ALL FILE DEFINITIONS. |
 * |                GENERATED BY STELCH WEB SERVER                |
 * |                                                              |
 * |--------------------------------------------------------------|
 */
 
 
module.exports = {
    "aac":"audio/acc",
    "abw":"application/x-abiword",
    "arc":"application/octet-stream",
    "avi":"video/x-msvideo",
    "azw":"application/vnd.amazon.ebook",
    "bin":"application/octet-stream",
    "bmp":"image/bmp",
    "bz":"application/x-bzip",
    "css":"text/css",
    "csv":"text/csv",
    "doc":"application/msword",
    "docx":"application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    "eot":"application/vnd.ms-fontobject",
    "epub":"application/epub+zip",
    "conf":"text/plain",
    "gif":"image/gif",
    "htm":"text/html",
    "html":"text/html",
    "ico":"image/x-icon",
    "ics":"text/calender",
    "jpeg":"image/jpeg",
    "jpg":"image/jpeg",
    "json":"application/json",
    "js":"text/javascript",
    "png":"image/png",
    "pdf":"application/pdf",
    "xml":"application/xml",
    "404":"text/html"
};