/*
 * |--------------------------------------------------------------|
 * |                                                              |
 * |                   DO NOT DELETE THIS FILE!                   |
 * |                                                              |
 * |              THIS IS THE CORE APPLICATION FILE               |
 * |                GENERATED BY STELCH WEB SERVER                |
 * |                                                              |
 * |--------------------------------------------------------------|
 */
 

const http = require("./modules/http");
const https = require("./modules/https");
const cline = require("./modules/cline");
const Proxy = require("./modules/proxy");
const logger = require("./modules/logger.js");
const fs = require("fs");
const config = JSON.parse(fs.readFileSync("config.yml").toString());

let highestport = 4015;
let portmap = {};

if(!!config['cline']){cline.start(http,https);}
logger.add(cline);
http.start(logger);


Proxy.start(logger,portmap);
for (let key in config['sites']) {
    if(config['sites'][key]['SSL']['enabled']===true){
        let host = key;
        https.start(cline,logger,{
            "port":highestport,
            "site":config['sites'][host],
            "domain":host
        });
        portmap[host]=highestport;
        highestport++;
    }
}