/*
 * |--------------------------------------------------------------|
 * |                                                              |
 * |                   DO NOT DELETE THIS FILE!                   |
 * |                                                              |
 * |    THIS IS THE CORE APPLICATION FILE FOR ALL API REQUESTS.   |
 * |                GENERATED BY STELCH WEB SERVER                |
 * |                                                              |
 * |--------------------------------------------------------------|
 */


var colors = {
    "red":"\u001b[31m",
    "reset":"\u001b[0m",
    "green":"\u001b[32m",
    "yellow":"\u001b[33m",
    "blue":"\u001b[34m",
    "magenta":"\u001b[35m",
    "cyan":"\u001b[36m",
    "white":"\u001b[37m"
};


module.exports = function(request,reply,headers,api_status){
    var time=Date.now();
    let GET = headers['url'].toString("utf-8").toLowerCase().split("/");
    reply.setHeader("X-Handled-By","swsAPI");
    reply.removeHeader('Content-Encoding');
    reply.removeHeader('Content-Type');
    reply.setHeader("Content-Encoding","application/json");
    reply.setHeader("Access-Control-Allow-Headers","*");
    reply.setHeader("Access-Control-Allow-Origin","*");
    reply.setHeader("Content-Type","text/json");

    let endpoint = GET[2];

    if(GET[2]==="handler"||true===false){
        reply.write(JSON.stringify({
            "error":"You are not permitted to use this endpoint.",
            "code":403
        }));
        reply.write("\r\n\r\n");
        reply.end(function(){
            request.destroy();
        });
    }else {
        try {
            require("../../modules/api/" + GET[2] + ".js")(GET.splice(2, GET.length), request, reply, headers,function(){
                if((Date.now()-time)>=1000){console.log("["+colors.red+"WARNING"+colors.reset+"] Slow endpoint detected at '"+headers['url'].split("/")[2]+"' took "+(Date.now()-time)+"ms to load.");}
                console.log("["+colors.yellow+"DISCONNECT:SSL"+colors.reset+"] " + headers['client_address'] + " Requested API '" + headers['url'] + " at " + Date.now());
                reply.end(function () {
                    request.destroy();
                    try {
                        delete require.cache[require.resolve(`../../modules/api/${endpoint}.js`)];
                    }catch (e){console.log(e);}
                });
            });
        } catch (e) {
            reply.write(JSON.stringify({
                "error": e.toString(),
                "code": 500
            }));
            reply.write("\r\n\r\n");
            reply.end(function () {
                request.destroy();
            });
        }
    }
};